// Code generated by ogen, DO NOT EDIT.

package ogenhosted

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddMemory implements addMemory operation.
	//
	// Extracts facts from conversation messages using single-pass additive extraction.
	//
	// POST /v3/memories/add/
	AddMemory(ctx context.Context, req *AddMemoryRequest) (AddMemoryRes, error)
	// DeleteAllMemories implements deleteAllMemories operation.
	//
	// Delete all memories for an identifier.
	//
	// DELETE /v1/memories/
	DeleteAllMemories(ctx context.Context, params DeleteAllMemoriesParams) (*DeleteAllResponse, error)
	// DeleteEntity implements deleteEntity operation.
	//
	// Cascade-delete all memories for entity.
	//
	// DELETE /v2/entities/{entity_type}/{entity_id}/
	DeleteEntity(ctx context.Context, params DeleteEntityParams) (DeleteEntityRes, error)
	// DeleteMemory implements deleteMemory operation.
	//
	// Remove a single memory record.
	//
	// DELETE /v1/memories/{memory_id}/
	DeleteMemory(ctx context.Context, params DeleteMemoryParams) (DeleteMemoryRes, error)
	// GetEntity implements getEntity operation.
	//
	// Get entity details.
	//
	// GET /v2/entities/{entity_type}/{entity_id}/
	GetEntity(ctx context.Context, params GetEntityParams) (GetEntityRes, error)
	// GetEventStatus implements getEventStatus operation.
	//
	// Retrieve final status of asynchronous operations.
	//
	// GET /v1/event/{event_id}/
	GetEventStatus(ctx context.Context, params GetEventStatusParams) (GetEventStatusRes, error)
	// GetMemories implements getMemories operation.
	//
	// Paginated retrieval of memories with optional filtering.
	//
	// POST /v3/memories/
	GetMemories(ctx context.Context, req OptGetMemoriesRequest) (GetMemoriesRes, error)
	// GetMemory implements getMemory operation.
	//
	// Fetch a specific memory record by ID.
	//
	// GET /v1/memories/{memory_id}/
	GetMemory(ctx context.Context, params GetMemoryParams) (GetMemoryRes, error)
	// GetMemoryHistory implements getMemoryHistory operation.
	//
	// Access memory change history.
	//
	// GET /v1/memories/{memory_id}/history/
	GetMemoryHistory(ctx context.Context, params GetMemoryHistoryParams) (GetMemoryHistoryRes, error)
	// SearchMemories implements searchMemories operation.
	//
	// Performs hybrid search combining semantic, BM25, and entity matching.
	//
	// POST /v3/memories/search/
	SearchMemories(ctx context.Context, req *SearchMemoriesRequest) (SearchMemoriesRes, error)
	// UpdateMemory implements updateMemory operation.
	//
	// Modify an existing memory record.
	//
	// PUT /v1/memories/{memory_id}/
	UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, params UpdateMemoryParams) (UpdateMemoryRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
