// Code generated by ogen, DO NOT EDIT.

package ogenhosted

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type AddMemoryBadRequest ErrorResponse

func (*AddMemoryBadRequest) addMemoryRes() {}

// Ref: #/components/schemas/AddMemoryRequest
type AddMemoryRequest struct {
	Messages []Message                   `json:"messages"`
	UserID   OptString                   `json:"user_id"`
	AgentID  OptString                   `json:"agent_id"`
	AppID    OptString                   `json:"app_id"`
	RunID    OptString                   `json:"run_id"`
	Metadata OptAddMemoryRequestMetadata `json:"metadata"`
	// Whether to infer facts from messages.
	Infer OptBool `json:"infer"`
}

// GetMessages returns the value of Messages.
func (s *AddMemoryRequest) GetMessages() []Message {
	return s.Messages
}

// GetUserID returns the value of UserID.
func (s *AddMemoryRequest) GetUserID() OptString {
	return s.UserID
}

// GetAgentID returns the value of AgentID.
func (s *AddMemoryRequest) GetAgentID() OptString {
	return s.AgentID
}

// GetAppID returns the value of AppID.
func (s *AddMemoryRequest) GetAppID() OptString {
	return s.AppID
}

// GetRunID returns the value of RunID.
func (s *AddMemoryRequest) GetRunID() OptString {
	return s.RunID
}

// GetMetadata returns the value of Metadata.
func (s *AddMemoryRequest) GetMetadata() OptAddMemoryRequestMetadata {
	return s.Metadata
}

// GetInfer returns the value of Infer.
func (s *AddMemoryRequest) GetInfer() OptBool {
	return s.Infer
}

// SetMessages sets the value of Messages.
func (s *AddMemoryRequest) SetMessages(val []Message) {
	s.Messages = val
}

// SetUserID sets the value of UserID.
func (s *AddMemoryRequest) SetUserID(val OptString) {
	s.UserID = val
}

// SetAgentID sets the value of AgentID.
func (s *AddMemoryRequest) SetAgentID(val OptString) {
	s.AgentID = val
}

// SetAppID sets the value of AppID.
func (s *AddMemoryRequest) SetAppID(val OptString) {
	s.AppID = val
}

// SetRunID sets the value of RunID.
func (s *AddMemoryRequest) SetRunID(val OptString) {
	s.RunID = val
}

// SetMetadata sets the value of Metadata.
func (s *AddMemoryRequest) SetMetadata(val OptAddMemoryRequestMetadata) {
	s.Metadata = val
}

// SetInfer sets the value of Infer.
func (s *AddMemoryRequest) SetInfer(val OptBool) {
	s.Infer = val
}

type AddMemoryRequestMetadata map[string]jx.Raw

func (s *AddMemoryRequestMetadata) init() AddMemoryRequestMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/AddMemoryResponse
type AddMemoryResponse struct {
	// Event ID for polling async operation status.
	EventID OptString         `json:"event_id"`
	Results []AddMemoryResult `json:"results"`
}

// GetEventID returns the value of EventID.
func (s *AddMemoryResponse) GetEventID() OptString {
	return s.EventID
}

// GetResults returns the value of Results.
func (s *AddMemoryResponse) GetResults() []AddMemoryResult {
	return s.Results
}

// SetEventID sets the value of EventID.
func (s *AddMemoryResponse) SetEventID(val OptString) {
	s.EventID = val
}

// SetResults sets the value of Results.
func (s *AddMemoryResponse) SetResults(val []AddMemoryResult) {
	s.Results = val
}

func (*AddMemoryResponse) addMemoryRes() {}

// Ref: #/components/schemas/AddMemoryResult
type AddMemoryResult struct {
	ID     OptString               `json:"id"`
	Memory OptString               `json:"memory"`
	Event  OptAddMemoryResultEvent `json:"event"`
}

// GetID returns the value of ID.
func (s *AddMemoryResult) GetID() OptString {
	return s.ID
}

// GetMemory returns the value of Memory.
func (s *AddMemoryResult) GetMemory() OptString {
	return s.Memory
}

// GetEvent returns the value of Event.
func (s *AddMemoryResult) GetEvent() OptAddMemoryResultEvent {
	return s.Event
}

// SetID sets the value of ID.
func (s *AddMemoryResult) SetID(val OptString) {
	s.ID = val
}

// SetMemory sets the value of Memory.
func (s *AddMemoryResult) SetMemory(val OptString) {
	s.Memory = val
}

// SetEvent sets the value of Event.
func (s *AddMemoryResult) SetEvent(val OptAddMemoryResultEvent) {
	s.Event = val
}

type AddMemoryResultEvent string

const (
	AddMemoryResultEventADD    AddMemoryResultEvent = "ADD"
	AddMemoryResultEventUPDATE AddMemoryResultEvent = "UPDATE"
	AddMemoryResultEventDELETE AddMemoryResultEvent = "DELETE"
	AddMemoryResultEventNOOP   AddMemoryResultEvent = "NOOP"
)

// AllValues returns all AddMemoryResultEvent values.
func (AddMemoryResultEvent) AllValues() []AddMemoryResultEvent {
	return []AddMemoryResultEvent{
		AddMemoryResultEventADD,
		AddMemoryResultEventUPDATE,
		AddMemoryResultEventDELETE,
		AddMemoryResultEventNOOP,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AddMemoryResultEvent) MarshalText() ([]byte, error) {
	switch s {
	case AddMemoryResultEventADD:
		return []byte(s), nil
	case AddMemoryResultEventUPDATE:
		return []byte(s), nil
	case AddMemoryResultEventDELETE:
		return []byte(s), nil
	case AddMemoryResultEventNOOP:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AddMemoryResultEvent) UnmarshalText(data []byte) error {
	switch AddMemoryResultEvent(data) {
	case AddMemoryResultEventADD:
		*s = AddMemoryResultEventADD
		return nil
	case AddMemoryResultEventUPDATE:
		*s = AddMemoryResultEventUPDATE
		return nil
	case AddMemoryResultEventDELETE:
		*s = AddMemoryResultEventDELETE
		return nil
	case AddMemoryResultEventNOOP:
		*s = AddMemoryResultEventNOOP
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type AddMemoryUnauthorized ErrorResponse

func (*AddMemoryUnauthorized) addMemoryRes() {}

// Ref: #/components/schemas/DeleteAllResponse
type DeleteAllResponse struct {
	Message      OptString `json:"message"`
	DeletedCount OptInt    `json:"deleted_count"`
}

// GetMessage returns the value of Message.
func (s *DeleteAllResponse) GetMessage() OptString {
	return s.Message
}

// GetDeletedCount returns the value of DeletedCount.
func (s *DeleteAllResponse) GetDeletedCount() OptInt {
	return s.DeletedCount
}

// SetMessage sets the value of Message.
func (s *DeleteAllResponse) SetMessage(val OptString) {
	s.Message = val
}

// SetDeletedCount sets the value of DeletedCount.
func (s *DeleteAllResponse) SetDeletedCount(val OptInt) {
	s.DeletedCount = val
}

type DeleteEntityEntityType string

const (
	DeleteEntityEntityTypeUser  DeleteEntityEntityType = "user"
	DeleteEntityEntityTypeAgent DeleteEntityEntityType = "agent"
	DeleteEntityEntityTypeApp   DeleteEntityEntityType = "app"
	DeleteEntityEntityTypeRun   DeleteEntityEntityType = "run"
)

// AllValues returns all DeleteEntityEntityType values.
func (DeleteEntityEntityType) AllValues() []DeleteEntityEntityType {
	return []DeleteEntityEntityType{
		DeleteEntityEntityTypeUser,
		DeleteEntityEntityTypeAgent,
		DeleteEntityEntityTypeApp,
		DeleteEntityEntityTypeRun,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DeleteEntityEntityType) MarshalText() ([]byte, error) {
	switch s {
	case DeleteEntityEntityTypeUser:
		return []byte(s), nil
	case DeleteEntityEntityTypeAgent:
		return []byte(s), nil
	case DeleteEntityEntityTypeApp:
		return []byte(s), nil
	case DeleteEntityEntityTypeRun:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DeleteEntityEntityType) UnmarshalText(data []byte) error {
	switch DeleteEntityEntityType(data) {
	case DeleteEntityEntityTypeUser:
		*s = DeleteEntityEntityTypeUser
		return nil
	case DeleteEntityEntityTypeAgent:
		*s = DeleteEntityEntityTypeAgent
		return nil
	case DeleteEntityEntityTypeApp:
		*s = DeleteEntityEntityTypeApp
		return nil
	case DeleteEntityEntityTypeRun:
		*s = DeleteEntityEntityTypeRun
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/DeleteResponse
type DeleteResponse struct {
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *DeleteResponse) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *DeleteResponse) SetMessage(val OptString) {
	s.Message = val
}

func (*DeleteResponse) deleteEntityRes() {}
func (*DeleteResponse) deleteMemoryRes() {}

// Ref: #/components/schemas/Entity
type Entity struct {
	Type        OptEntityType `json:"type"`
	ID          OptString     `json:"id"`
	MemoryCount OptInt        `json:"memory_count"`
	CreatedAt   OptDateTime   `json:"created_at"`
	UpdatedAt   OptDateTime   `json:"updated_at"`
}

// GetType returns the value of Type.
func (s *Entity) GetType() OptEntityType {
	return s.Type
}

// GetID returns the value of ID.
func (s *Entity) GetID() OptString {
	return s.ID
}

// GetMemoryCount returns the value of MemoryCount.
func (s *Entity) GetMemoryCount() OptInt {
	return s.MemoryCount
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Entity) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Entity) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetType sets the value of Type.
func (s *Entity) SetType(val OptEntityType) {
	s.Type = val
}

// SetID sets the value of ID.
func (s *Entity) SetID(val OptString) {
	s.ID = val
}

// SetMemoryCount sets the value of MemoryCount.
func (s *Entity) SetMemoryCount(val OptInt) {
	s.MemoryCount = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Entity) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Entity) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Entity) getEntityRes() {}

type EntityType string

const (
	EntityTypeUser  EntityType = "user"
	EntityTypeAgent EntityType = "agent"
	EntityTypeApp   EntityType = "app"
	EntityTypeRun   EntityType = "run"
)

// AllValues returns all EntityType values.
func (EntityType) AllValues() []EntityType {
	return []EntityType{
		EntityTypeUser,
		EntityTypeAgent,
		EntityTypeApp,
		EntityTypeRun,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EntityType) MarshalText() ([]byte, error) {
	switch s {
	case EntityTypeUser:
		return []byte(s), nil
	case EntityTypeAgent:
		return []byte(s), nil
	case EntityTypeApp:
		return []byte(s), nil
	case EntityTypeRun:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EntityType) UnmarshalText(data []byte) error {
	switch EntityType(data) {
	case EntityTypeUser:
		*s = EntityTypeUser
		return nil
	case EntityTypeAgent:
		*s = EntityTypeAgent
		return nil
	case EntityTypeApp:
		*s = EntityTypeApp
		return nil
	case EntityTypeRun:
		*s = EntityTypeRun
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Detail OptString `json:"detail"`
	Code   OptString `json:"code"`
}

// GetDetail returns the value of Detail.
func (s *ErrorResponse) GetDetail() OptString {
	return s.Detail
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() OptString {
	return s.Code
}

// SetDetail sets the value of Detail.
func (s *ErrorResponse) SetDetail(val OptString) {
	s.Detail = val
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val OptString) {
	s.Code = val
}

func (*ErrorResponse) deleteEntityRes()     {}
func (*ErrorResponse) deleteMemoryRes()     {}
func (*ErrorResponse) getEntityRes()        {}
func (*ErrorResponse) getEventStatusRes()   {}
func (*ErrorResponse) getMemoriesRes()      {}
func (*ErrorResponse) getMemoryHistoryRes() {}
func (*ErrorResponse) getMemoryRes()        {}
func (*ErrorResponse) updateMemoryRes()     {}

// Ref: #/components/schemas/EventStatus
type EventStatus struct {
	EventID     OptString            `json:"event_id"`
	Status      OptEventStatusStatus `json:"status"`
	Results     []AddMemoryResult    `json:"results"`
	Error       OptNilString         `json:"error"`
	CreatedAt   OptDateTime          `json:"created_at"`
	CompletedAt OptNilDateTime       `json:"completed_at"`
}

// GetEventID returns the value of EventID.
func (s *EventStatus) GetEventID() OptString {
	return s.EventID
}

// GetStatus returns the value of Status.
func (s *EventStatus) GetStatus() OptEventStatusStatus {
	return s.Status
}

// GetResults returns the value of Results.
func (s *EventStatus) GetResults() []AddMemoryResult {
	return s.Results
}

// GetError returns the value of Error.
func (s *EventStatus) GetError() OptNilString {
	return s.Error
}

// GetCreatedAt returns the value of CreatedAt.
func (s *EventStatus) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *EventStatus) GetCompletedAt() OptNilDateTime {
	return s.CompletedAt
}

// SetEventID sets the value of EventID.
func (s *EventStatus) SetEventID(val OptString) {
	s.EventID = val
}

// SetStatus sets the value of Status.
func (s *EventStatus) SetStatus(val OptEventStatusStatus) {
	s.Status = val
}

// SetResults sets the value of Results.
func (s *EventStatus) SetResults(val []AddMemoryResult) {
	s.Results = val
}

// SetError sets the value of Error.
func (s *EventStatus) SetError(val OptNilString) {
	s.Error = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *EventStatus) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *EventStatus) SetCompletedAt(val OptNilDateTime) {
	s.CompletedAt = val
}

func (*EventStatus) getEventStatusRes() {}

type EventStatusStatus string

const (
	EventStatusStatusPending    EventStatusStatus = "pending"
	EventStatusStatusProcessing EventStatusStatus = "processing"
	EventStatusStatusCompleted  EventStatusStatus = "completed"
	EventStatusStatusFailed     EventStatusStatus = "failed"
)

// AllValues returns all EventStatusStatus values.
func (EventStatusStatus) AllValues() []EventStatusStatus {
	return []EventStatusStatus{
		EventStatusStatusPending,
		EventStatusStatusProcessing,
		EventStatusStatusCompleted,
		EventStatusStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s EventStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case EventStatusStatusPending:
		return []byte(s), nil
	case EventStatusStatusProcessing:
		return []byte(s), nil
	case EventStatusStatusCompleted:
		return []byte(s), nil
	case EventStatusStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *EventStatusStatus) UnmarshalText(data []byte) error {
	switch EventStatusStatus(data) {
	case EventStatusStatusPending:
		*s = EventStatusStatusPending
		return nil
	case EventStatusStatusProcessing:
		*s = EventStatusStatusProcessing
		return nil
	case EventStatusStatusCompleted:
		*s = EventStatusStatusCompleted
		return nil
	case EventStatusStatusFailed:
		*s = EventStatusStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/FilterCondition
type FilterCondition map[string]jx.Raw

func (s *FilterCondition) init() FilterCondition {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/Filters
type Filters struct {
	UserID  OptString         `json:"user_id"`
	AgentID OptString         `json:"agent_id"`
	AppID   OptString         `json:"app_id"`
	RunID   OptString         `json:"run_id"`
	AND     []FilterCondition `json:"AND"`
	OR      []FilterCondition `json:"OR"`
}

// GetUserID returns the value of UserID.
func (s *Filters) GetUserID() OptString {
	return s.UserID
}

// GetAgentID returns the value of AgentID.
func (s *Filters) GetAgentID() OptString {
	return s.AgentID
}

// GetAppID returns the value of AppID.
func (s *Filters) GetAppID() OptString {
	return s.AppID
}

// GetRunID returns the value of RunID.
func (s *Filters) GetRunID() OptString {
	return s.RunID
}

// GetAND returns the value of AND.
func (s *Filters) GetAND() []FilterCondition {
	return s.AND
}

// GetOR returns the value of OR.
func (s *Filters) GetOR() []FilterCondition {
	return s.OR
}

// SetUserID sets the value of UserID.
func (s *Filters) SetUserID(val OptString) {
	s.UserID = val
}

// SetAgentID sets the value of AgentID.
func (s *Filters) SetAgentID(val OptString) {
	s.AgentID = val
}

// SetAppID sets the value of AppID.
func (s *Filters) SetAppID(val OptString) {
	s.AppID = val
}

// SetRunID sets the value of RunID.
func (s *Filters) SetRunID(val OptString) {
	s.RunID = val
}

// SetAND sets the value of AND.
func (s *Filters) SetAND(val []FilterCondition) {
	s.AND = val
}

// SetOR sets the value of OR.
func (s *Filters) SetOR(val []FilterCondition) {
	s.OR = val
}

type GetEntityEntityType string

const (
	GetEntityEntityTypeUser  GetEntityEntityType = "user"
	GetEntityEntityTypeAgent GetEntityEntityType = "agent"
	GetEntityEntityTypeApp   GetEntityEntityType = "app"
	GetEntityEntityTypeRun   GetEntityEntityType = "run"
)

// AllValues returns all GetEntityEntityType values.
func (GetEntityEntityType) AllValues() []GetEntityEntityType {
	return []GetEntityEntityType{
		GetEntityEntityTypeUser,
		GetEntityEntityTypeAgent,
		GetEntityEntityTypeApp,
		GetEntityEntityTypeRun,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s GetEntityEntityType) MarshalText() ([]byte, error) {
	switch s {
	case GetEntityEntityTypeUser:
		return []byte(s), nil
	case GetEntityEntityTypeAgent:
		return []byte(s), nil
	case GetEntityEntityTypeApp:
		return []byte(s), nil
	case GetEntityEntityTypeRun:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *GetEntityEntityType) UnmarshalText(data []byte) error {
	switch GetEntityEntityType(data) {
	case GetEntityEntityTypeUser:
		*s = GetEntityEntityTypeUser
		return nil
	case GetEntityEntityTypeAgent:
		*s = GetEntityEntityTypeAgent
		return nil
	case GetEntityEntityTypeApp:
		*s = GetEntityEntityTypeApp
		return nil
	case GetEntityEntityTypeRun:
		*s = GetEntityEntityTypeRun
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/GetMemoriesRequest
type GetMemoriesRequest struct {
	Filters  OptFilters `json:"filters"`
	Page     OptInt     `json:"page"`
	PageSize OptInt     `json:"page_size"`
}

// GetFilters returns the value of Filters.
func (s *GetMemoriesRequest) GetFilters() OptFilters {
	return s.Filters
}

// GetPage returns the value of Page.
func (s *GetMemoriesRequest) GetPage() OptInt {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *GetMemoriesRequest) GetPageSize() OptInt {
	return s.PageSize
}

// SetFilters sets the value of Filters.
func (s *GetMemoriesRequest) SetFilters(val OptFilters) {
	s.Filters = val
}

// SetPage sets the value of Page.
func (s *GetMemoriesRequest) SetPage(val OptInt) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *GetMemoriesRequest) SetPageSize(val OptInt) {
	s.PageSize = val
}

// Ref: #/components/schemas/GetMemoriesResponse
type GetMemoriesResponse struct {
	Count    OptInt       `json:"count"`
	Next     OptNilString `json:"next"`
	Previous OptNilString `json:"previous"`
	Results  []MemoryItem `json:"results"`
}

// GetCount returns the value of Count.
func (s *GetMemoriesResponse) GetCount() OptInt {
	return s.Count
}

// GetNext returns the value of Next.
func (s *GetMemoriesResponse) GetNext() OptNilString {
	return s.Next
}

// GetPrevious returns the value of Previous.
func (s *GetMemoriesResponse) GetPrevious() OptNilString {
	return s.Previous
}

// GetResults returns the value of Results.
func (s *GetMemoriesResponse) GetResults() []MemoryItem {
	return s.Results
}

// SetCount sets the value of Count.
func (s *GetMemoriesResponse) SetCount(val OptInt) {
	s.Count = val
}

// SetNext sets the value of Next.
func (s *GetMemoriesResponse) SetNext(val OptNilString) {
	s.Next = val
}

// SetPrevious sets the value of Previous.
func (s *GetMemoriesResponse) SetPrevious(val OptNilString) {
	s.Previous = val
}

// SetResults sets the value of Results.
func (s *GetMemoriesResponse) SetResults(val []MemoryItem) {
	s.Results = val
}

func (*GetMemoriesResponse) getMemoriesRes() {}

type GetMemoryHistoryOKApplicationJSON []HistoryItem

func (*GetMemoryHistoryOKApplicationJSON) getMemoryHistoryRes() {}

// Ref: #/components/schemas/HistoryItem
type HistoryItem struct {
	ID        OptString           `json:"id"`
	MemoryID  OptString           `json:"memory_id"`
	OldMemory OptNilString        `json:"old_memory"`
	NewMemory OptString           `json:"new_memory"`
	Event     OptHistoryItemEvent `json:"event"`
	CreatedAt OptDateTime         `json:"created_at"`
}

// GetID returns the value of ID.
func (s *HistoryItem) GetID() OptString {
	return s.ID
}

// GetMemoryID returns the value of MemoryID.
func (s *HistoryItem) GetMemoryID() OptString {
	return s.MemoryID
}

// GetOldMemory returns the value of OldMemory.
func (s *HistoryItem) GetOldMemory() OptNilString {
	return s.OldMemory
}

// GetNewMemory returns the value of NewMemory.
func (s *HistoryItem) GetNewMemory() OptString {
	return s.NewMemory
}

// GetEvent returns the value of Event.
func (s *HistoryItem) GetEvent() OptHistoryItemEvent {
	return s.Event
}

// GetCreatedAt returns the value of CreatedAt.
func (s *HistoryItem) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *HistoryItem) SetID(val OptString) {
	s.ID = val
}

// SetMemoryID sets the value of MemoryID.
func (s *HistoryItem) SetMemoryID(val OptString) {
	s.MemoryID = val
}

// SetOldMemory sets the value of OldMemory.
func (s *HistoryItem) SetOldMemory(val OptNilString) {
	s.OldMemory = val
}

// SetNewMemory sets the value of NewMemory.
func (s *HistoryItem) SetNewMemory(val OptString) {
	s.NewMemory = val
}

// SetEvent sets the value of Event.
func (s *HistoryItem) SetEvent(val OptHistoryItemEvent) {
	s.Event = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *HistoryItem) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

type HistoryItemEvent string

const (
	HistoryItemEventADD    HistoryItemEvent = "ADD"
	HistoryItemEventUPDATE HistoryItemEvent = "UPDATE"
	HistoryItemEventDELETE HistoryItemEvent = "DELETE"
)

// AllValues returns all HistoryItemEvent values.
func (HistoryItemEvent) AllValues() []HistoryItemEvent {
	return []HistoryItemEvent{
		HistoryItemEventADD,
		HistoryItemEventUPDATE,
		HistoryItemEventDELETE,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HistoryItemEvent) MarshalText() ([]byte, error) {
	switch s {
	case HistoryItemEventADD:
		return []byte(s), nil
	case HistoryItemEventUPDATE:
		return []byte(s), nil
	case HistoryItemEventDELETE:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HistoryItemEvent) UnmarshalText(data []byte) error {
	switch HistoryItemEvent(data) {
	case HistoryItemEventADD:
		*s = HistoryItemEventADD
		return nil
	case HistoryItemEventUPDATE:
		*s = HistoryItemEventUPDATE
		return nil
	case HistoryItemEventDELETE:
		*s = HistoryItemEventDELETE
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MemoryItem
type MemoryItem struct {
	ID         OptString             `json:"id"`
	Memory     OptString             `json:"memory"`
	UserID     OptString             `json:"user_id"`
	AgentID    OptString             `json:"agent_id"`
	AppID      OptString             `json:"app_id"`
	RunID      OptString             `json:"run_id"`
	Hash       OptString             `json:"hash"`
	Categories []string              `json:"categories"`
	Metadata   OptMemoryItemMetadata `json:"metadata"`
	CreatedAt  OptDateTime           `json:"created_at"`
	UpdatedAt  OptDateTime           `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *MemoryItem) GetID() OptString {
	return s.ID
}

// GetMemory returns the value of Memory.
func (s *MemoryItem) GetMemory() OptString {
	return s.Memory
}

// GetUserID returns the value of UserID.
func (s *MemoryItem) GetUserID() OptString {
	return s.UserID
}

// GetAgentID returns the value of AgentID.
func (s *MemoryItem) GetAgentID() OptString {
	return s.AgentID
}

// GetAppID returns the value of AppID.
func (s *MemoryItem) GetAppID() OptString {
	return s.AppID
}

// GetRunID returns the value of RunID.
func (s *MemoryItem) GetRunID() OptString {
	return s.RunID
}

// GetHash returns the value of Hash.
func (s *MemoryItem) GetHash() OptString {
	return s.Hash
}

// GetCategories returns the value of Categories.
func (s *MemoryItem) GetCategories() []string {
	return s.Categories
}

// GetMetadata returns the value of Metadata.
func (s *MemoryItem) GetMetadata() OptMemoryItemMetadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *MemoryItem) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *MemoryItem) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *MemoryItem) SetID(val OptString) {
	s.ID = val
}

// SetMemory sets the value of Memory.
func (s *MemoryItem) SetMemory(val OptString) {
	s.Memory = val
}

// SetUserID sets the value of UserID.
func (s *MemoryItem) SetUserID(val OptString) {
	s.UserID = val
}

// SetAgentID sets the value of AgentID.
func (s *MemoryItem) SetAgentID(val OptString) {
	s.AgentID = val
}

// SetAppID sets the value of AppID.
func (s *MemoryItem) SetAppID(val OptString) {
	s.AppID = val
}

// SetRunID sets the value of RunID.
func (s *MemoryItem) SetRunID(val OptString) {
	s.RunID = val
}

// SetHash sets the value of Hash.
func (s *MemoryItem) SetHash(val OptString) {
	s.Hash = val
}

// SetCategories sets the value of Categories.
func (s *MemoryItem) SetCategories(val []string) {
	s.Categories = val
}

// SetMetadata sets the value of Metadata.
func (s *MemoryItem) SetMetadata(val OptMemoryItemMetadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *MemoryItem) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *MemoryItem) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*MemoryItem) getMemoryRes()    {}
func (*MemoryItem) updateMemoryRes() {}

type MemoryItemMetadata map[string]jx.Raw

func (s *MemoryItemMetadata) init() MemoryItemMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/Message
type Message struct {
	Role    MessageRole `json:"role"`
	Content string      `json:"content"`
}

// GetRole returns the value of Role.
func (s *Message) GetRole() MessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *Message) GetContent() string {
	return s.Content
}

// SetRole sets the value of Role.
func (s *Message) SetRole(val MessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *Message) SetContent(val string) {
	s.Content = val
}

type MessageRole string

const (
	MessageRoleUser      MessageRole = "user"
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
)

// AllValues returns all MessageRole values.
func (MessageRole) AllValues() []MessageRole {
	return []MessageRole{
		MessageRoleUser,
		MessageRoleAssistant,
		MessageRoleSystem,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MessageRole) MarshalText() ([]byte, error) {
	switch s {
	case MessageRoleUser:
		return []byte(s), nil
	case MessageRoleAssistant:
		return []byte(s), nil
	case MessageRoleSystem:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MessageRole) UnmarshalText(data []byte) error {
	switch MessageRole(data) {
	case MessageRoleUser:
		*s = MessageRoleUser
		return nil
	case MessageRoleAssistant:
		*s = MessageRoleAssistant
		return nil
	case MessageRoleSystem:
		*s = MessageRoleSystem
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptAddMemoryRequestMetadata returns new OptAddMemoryRequestMetadata with value set to v.
func NewOptAddMemoryRequestMetadata(v AddMemoryRequestMetadata) OptAddMemoryRequestMetadata {
	return OptAddMemoryRequestMetadata{
		Value: v,
		Set:   true,
	}
}

// OptAddMemoryRequestMetadata is optional AddMemoryRequestMetadata.
type OptAddMemoryRequestMetadata struct {
	Value AddMemoryRequestMetadata
	Set   bool
}

// IsSet returns true if OptAddMemoryRequestMetadata was set.
func (o OptAddMemoryRequestMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddMemoryRequestMetadata) Reset() {
	var v AddMemoryRequestMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddMemoryRequestMetadata) SetTo(v AddMemoryRequestMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddMemoryRequestMetadata) Get() (v AddMemoryRequestMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddMemoryRequestMetadata) Or(d AddMemoryRequestMetadata) AddMemoryRequestMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptAddMemoryResultEvent returns new OptAddMemoryResultEvent with value set to v.
func NewOptAddMemoryResultEvent(v AddMemoryResultEvent) OptAddMemoryResultEvent {
	return OptAddMemoryResultEvent{
		Value: v,
		Set:   true,
	}
}

// OptAddMemoryResultEvent is optional AddMemoryResultEvent.
type OptAddMemoryResultEvent struct {
	Value AddMemoryResultEvent
	Set   bool
}

// IsSet returns true if OptAddMemoryResultEvent was set.
func (o OptAddMemoryResultEvent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptAddMemoryResultEvent) Reset() {
	var v AddMemoryResultEvent
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptAddMemoryResultEvent) SetTo(v AddMemoryResultEvent) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptAddMemoryResultEvent) Get() (v AddMemoryResultEvent, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptAddMemoryResultEvent) Or(d AddMemoryResultEvent) AddMemoryResultEvent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEntityType returns new OptEntityType with value set to v.
func NewOptEntityType(v EntityType) OptEntityType {
	return OptEntityType{
		Value: v,
		Set:   true,
	}
}

// OptEntityType is optional EntityType.
type OptEntityType struct {
	Value EntityType
	Set   bool
}

// IsSet returns true if OptEntityType was set.
func (o OptEntityType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEntityType) Reset() {
	var v EntityType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEntityType) SetTo(v EntityType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEntityType) Get() (v EntityType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEntityType) Or(d EntityType) EntityType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEventStatusStatus returns new OptEventStatusStatus with value set to v.
func NewOptEventStatusStatus(v EventStatusStatus) OptEventStatusStatus {
	return OptEventStatusStatus{
		Value: v,
		Set:   true,
	}
}

// OptEventStatusStatus is optional EventStatusStatus.
type OptEventStatusStatus struct {
	Value EventStatusStatus
	Set   bool
}

// IsSet returns true if OptEventStatusStatus was set.
func (o OptEventStatusStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEventStatusStatus) Reset() {
	var v EventStatusStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEventStatusStatus) SetTo(v EventStatusStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEventStatusStatus) Get() (v EventStatusStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEventStatusStatus) Or(d EventStatusStatus) EventStatusStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFilters returns new OptFilters with value set to v.
func NewOptFilters(v Filters) OptFilters {
	return OptFilters{
		Value: v,
		Set:   true,
	}
}

// OptFilters is optional Filters.
type OptFilters struct {
	Value Filters
	Set   bool
}

// IsSet returns true if OptFilters was set.
func (o OptFilters) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFilters) Reset() {
	var v Filters
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFilters) SetTo(v Filters) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFilters) Get() (v Filters, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFilters) Or(d Filters) Filters {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat32 returns new OptFloat32 with value set to v.
func NewOptFloat32(v float32) OptFloat32 {
	return OptFloat32{
		Value: v,
		Set:   true,
	}
}

// OptFloat32 is optional float32.
type OptFloat32 struct {
	Value float32
	Set   bool
}

// IsSet returns true if OptFloat32 was set.
func (o OptFloat32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat32) Reset() {
	var v float32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat32) SetTo(v float32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat32) Get() (v float32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat32) Or(d float32) float32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptGetMemoriesRequest returns new OptGetMemoriesRequest with value set to v.
func NewOptGetMemoriesRequest(v GetMemoriesRequest) OptGetMemoriesRequest {
	return OptGetMemoriesRequest{
		Value: v,
		Set:   true,
	}
}

// OptGetMemoriesRequest is optional GetMemoriesRequest.
type OptGetMemoriesRequest struct {
	Value GetMemoriesRequest
	Set   bool
}

// IsSet returns true if OptGetMemoriesRequest was set.
func (o OptGetMemoriesRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptGetMemoriesRequest) Reset() {
	var v GetMemoriesRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptGetMemoriesRequest) SetTo(v GetMemoriesRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptGetMemoriesRequest) Get() (v GetMemoriesRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptGetMemoriesRequest) Or(d GetMemoriesRequest) GetMemoriesRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptHistoryItemEvent returns new OptHistoryItemEvent with value set to v.
func NewOptHistoryItemEvent(v HistoryItemEvent) OptHistoryItemEvent {
	return OptHistoryItemEvent{
		Value: v,
		Set:   true,
	}
}

// OptHistoryItemEvent is optional HistoryItemEvent.
type OptHistoryItemEvent struct {
	Value HistoryItemEvent
	Set   bool
}

// IsSet returns true if OptHistoryItemEvent was set.
func (o OptHistoryItemEvent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptHistoryItemEvent) Reset() {
	var v HistoryItemEvent
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptHistoryItemEvent) SetTo(v HistoryItemEvent) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptHistoryItemEvent) Get() (v HistoryItemEvent, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptHistoryItemEvent) Or(d HistoryItemEvent) HistoryItemEvent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMemoryItemMetadata returns new OptMemoryItemMetadata with value set to v.
func NewOptMemoryItemMetadata(v MemoryItemMetadata) OptMemoryItemMetadata {
	return OptMemoryItemMetadata{
		Value: v,
		Set:   true,
	}
}

// OptMemoryItemMetadata is optional MemoryItemMetadata.
type OptMemoryItemMetadata struct {
	Value MemoryItemMetadata
	Set   bool
}

// IsSet returns true if OptMemoryItemMetadata was set.
func (o OptMemoryItemMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMemoryItemMetadata) Reset() {
	var v MemoryItemMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMemoryItemMetadata) SetTo(v MemoryItemMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMemoryItemMetadata) Get() (v MemoryItemMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMemoryItemMetadata) Or(d MemoryItemMetadata) MemoryItemMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSearchResultMetadata returns new OptSearchResultMetadata with value set to v.
func NewOptSearchResultMetadata(v SearchResultMetadata) OptSearchResultMetadata {
	return OptSearchResultMetadata{
		Value: v,
		Set:   true,
	}
}

// OptSearchResultMetadata is optional SearchResultMetadata.
type OptSearchResultMetadata struct {
	Value SearchResultMetadata
	Set   bool
}

// IsSet returns true if OptSearchResultMetadata was set.
func (o OptSearchResultMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSearchResultMetadata) Reset() {
	var v SearchResultMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSearchResultMetadata) SetTo(v SearchResultMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSearchResultMetadata) Get() (v SearchResultMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSearchResultMetadata) Or(d SearchResultMetadata) SearchResultMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type SearchMemoriesBadRequest ErrorResponse

func (*SearchMemoriesBadRequest) searchMemoriesRes() {}

// Ref: #/components/schemas/SearchMemoriesRequest
type SearchMemoriesRequest struct {
	Query     string     `json:"query"`
	Filters   OptFilters `json:"filters"`
	TopK      OptInt     `json:"top_k"`
	Rerank    OptBool    `json:"rerank"`
	Threshold OptFloat32 `json:"threshold"`
}

// GetQuery returns the value of Query.
func (s *SearchMemoriesRequest) GetQuery() string {
	return s.Query
}

// GetFilters returns the value of Filters.
func (s *SearchMemoriesRequest) GetFilters() OptFilters {
	return s.Filters
}

// GetTopK returns the value of TopK.
func (s *SearchMemoriesRequest) GetTopK() OptInt {
	return s.TopK
}

// GetRerank returns the value of Rerank.
func (s *SearchMemoriesRequest) GetRerank() OptBool {
	return s.Rerank
}

// GetThreshold returns the value of Threshold.
func (s *SearchMemoriesRequest) GetThreshold() OptFloat32 {
	return s.Threshold
}

// SetQuery sets the value of Query.
func (s *SearchMemoriesRequest) SetQuery(val string) {
	s.Query = val
}

// SetFilters sets the value of Filters.
func (s *SearchMemoriesRequest) SetFilters(val OptFilters) {
	s.Filters = val
}

// SetTopK sets the value of TopK.
func (s *SearchMemoriesRequest) SetTopK(val OptInt) {
	s.TopK = val
}

// SetRerank sets the value of Rerank.
func (s *SearchMemoriesRequest) SetRerank(val OptBool) {
	s.Rerank = val
}

// SetThreshold sets the value of Threshold.
func (s *SearchMemoriesRequest) SetThreshold(val OptFloat32) {
	s.Threshold = val
}

// Ref: #/components/schemas/SearchMemoriesResponse
type SearchMemoriesResponse struct {
	Results []SearchResult `json:"results"`
}

// GetResults returns the value of Results.
func (s *SearchMemoriesResponse) GetResults() []SearchResult {
	return s.Results
}

// SetResults sets the value of Results.
func (s *SearchMemoriesResponse) SetResults(val []SearchResult) {
	s.Results = val
}

func (*SearchMemoriesResponse) searchMemoriesRes() {}

type SearchMemoriesUnauthorized ErrorResponse

func (*SearchMemoriesUnauthorized) searchMemoriesRes() {}

// Ref: #/components/schemas/SearchResult
type SearchResult struct {
	ID         OptString               `json:"id"`
	Memory     OptString               `json:"memory"`
	UserID     OptString               `json:"user_id"`
	AgentID    OptString               `json:"agent_id"`
	AppID      OptString               `json:"app_id"`
	RunID      OptString               `json:"run_id"`
	Hash       OptString               `json:"hash"`
	Categories []string                `json:"categories"`
	Metadata   OptSearchResultMetadata `json:"metadata"`
	CreatedAt  OptDateTime             `json:"created_at"`
	UpdatedAt  OptDateTime             `json:"updated_at"`
	Score      OptFloat32              `json:"score"`
}

// GetID returns the value of ID.
func (s *SearchResult) GetID() OptString {
	return s.ID
}

// GetMemory returns the value of Memory.
func (s *SearchResult) GetMemory() OptString {
	return s.Memory
}

// GetUserID returns the value of UserID.
func (s *SearchResult) GetUserID() OptString {
	return s.UserID
}

// GetAgentID returns the value of AgentID.
func (s *SearchResult) GetAgentID() OptString {
	return s.AgentID
}

// GetAppID returns the value of AppID.
func (s *SearchResult) GetAppID() OptString {
	return s.AppID
}

// GetRunID returns the value of RunID.
func (s *SearchResult) GetRunID() OptString {
	return s.RunID
}

// GetHash returns the value of Hash.
func (s *SearchResult) GetHash() OptString {
	return s.Hash
}

// GetCategories returns the value of Categories.
func (s *SearchResult) GetCategories() []string {
	return s.Categories
}

// GetMetadata returns the value of Metadata.
func (s *SearchResult) GetMetadata() OptSearchResultMetadata {
	return s.Metadata
}

// GetCreatedAt returns the value of CreatedAt.
func (s *SearchResult) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *SearchResult) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// GetScore returns the value of Score.
func (s *SearchResult) GetScore() OptFloat32 {
	return s.Score
}

// SetID sets the value of ID.
func (s *SearchResult) SetID(val OptString) {
	s.ID = val
}

// SetMemory sets the value of Memory.
func (s *SearchResult) SetMemory(val OptString) {
	s.Memory = val
}

// SetUserID sets the value of UserID.
func (s *SearchResult) SetUserID(val OptString) {
	s.UserID = val
}

// SetAgentID sets the value of AgentID.
func (s *SearchResult) SetAgentID(val OptString) {
	s.AgentID = val
}

// SetAppID sets the value of AppID.
func (s *SearchResult) SetAppID(val OptString) {
	s.AppID = val
}

// SetRunID sets the value of RunID.
func (s *SearchResult) SetRunID(val OptString) {
	s.RunID = val
}

// SetHash sets the value of Hash.
func (s *SearchResult) SetHash(val OptString) {
	s.Hash = val
}

// SetCategories sets the value of Categories.
func (s *SearchResult) SetCategories(val []string) {
	s.Categories = val
}

// SetMetadata sets the value of Metadata.
func (s *SearchResult) SetMetadata(val OptSearchResultMetadata) {
	s.Metadata = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *SearchResult) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *SearchResult) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

// SetScore sets the value of Score.
func (s *SearchResult) SetScore(val OptFloat32) {
	s.Score = val
}

type SearchResultMetadata map[string]jx.Raw

func (s *SearchResultMetadata) init() SearchResultMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type TokenAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *TokenAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *TokenAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *TokenAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *TokenAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/UpdateMemoryRequest
type UpdateMemoryRequest struct {
	Text string `json:"text"`
}

// GetText returns the value of Text.
func (s *UpdateMemoryRequest) GetText() string {
	return s.Text
}

// SetText sets the value of Text.
func (s *UpdateMemoryRequest) SetText(val string) {
	s.Text = val
}
