// Code generated by ogen, DO NOT EDIT.

package ogenhosted

// setDefaults set default value of fields.
func (s *AddMemoryRequest) setDefaults() {
	{
		val := bool(true)
		s.Infer.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *GetMemoriesRequest) setDefaults() {
	{
		val := int(1)
		s.Page.SetTo(val)
	}
	{
		val := int(100)
		s.PageSize.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SearchMemoriesRequest) setDefaults() {
	{
		val := int(10)
		s.TopK.SetTo(val)
	}
	{
		val := bool(false)
		s.Rerank.SetTo(val)
	}
}
