// Code generated by ogen, DO NOT EDIT.

package ogenhosted

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleTokenAuth handles TokenAuth security.
	// Token-based authentication. Use format: Token.
	HandleTokenAuth(ctx context.Context, operationName OperationName, t TokenAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesTokenAuth is a private map storing roles per operation.
var operationRolesTokenAuth = map[string][]string{
	AddMemoryOperation:         []string{},
	DeleteAllMemoriesOperation: []string{},
	DeleteEntityOperation:      []string{},
	DeleteMemoryOperation:      []string{},
	GetEntityOperation:         []string{},
	GetEventStatusOperation:    []string{},
	GetMemoriesOperation:       []string{},
	GetMemoryOperation:         []string{},
	GetMemoryHistoryOperation:  []string{},
	SearchMemoriesOperation:    []string{},
	UpdateMemoryOperation:      []string{},
}

// GetRolesForTokenAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForTokenAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForTokenAuth(operation string) []string {
	roles, ok := operationRolesTokenAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityTokenAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t TokenAuth
	const parameterName = "Authorization"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesTokenAuth[operationName]
	rctx, err := s.sec.HandleTokenAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// TokenAuth provides TokenAuth security value.
	// Token-based authentication. Use format: Token.
	TokenAuth(ctx context.Context, operationName OperationName) (TokenAuth, error)
}

func (s *Client) securityTokenAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.TokenAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"TokenAuth\"")
	}
	req.Header.Set("Authorization", t.APIKey)
	return nil
}
