// Code generated by ogen, DO NOT EDIT.

package ogenhosted

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddMemory implements addMemory operation.
//
// Extracts facts from conversation messages using single-pass additive extraction.
//
// POST /v3/memories/add/
func (UnimplementedHandler) AddMemory(ctx context.Context, req *AddMemoryRequest) (r AddMemoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAllMemories implements deleteAllMemories operation.
//
// Delete all memories for an identifier.
//
// DELETE /v1/memories/
func (UnimplementedHandler) DeleteAllMemories(ctx context.Context, params DeleteAllMemoriesParams) (r *DeleteAllResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEntity implements deleteEntity operation.
//
// Cascade-delete all memories for entity.
//
// DELETE /v2/entities/{entity_type}/{entity_id}/
func (UnimplementedHandler) DeleteEntity(ctx context.Context, params DeleteEntityParams) (r DeleteEntityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMemory implements deleteMemory operation.
//
// Remove a single memory record.
//
// DELETE /v1/memories/{memory_id}/
func (UnimplementedHandler) DeleteMemory(ctx context.Context, params DeleteMemoryParams) (r DeleteMemoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEntity implements getEntity operation.
//
// Get entity details.
//
// GET /v2/entities/{entity_type}/{entity_id}/
func (UnimplementedHandler) GetEntity(ctx context.Context, params GetEntityParams) (r GetEntityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventStatus implements getEventStatus operation.
//
// Retrieve final status of asynchronous operations.
//
// GET /v1/event/{event_id}/
func (UnimplementedHandler) GetEventStatus(ctx context.Context, params GetEventStatusParams) (r GetEventStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemories implements getMemories operation.
//
// Paginated retrieval of memories with optional filtering.
//
// POST /v3/memories/
func (UnimplementedHandler) GetMemories(ctx context.Context, req OptGetMemoriesRequest) (r GetMemoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemory implements getMemory operation.
//
// Fetch a specific memory record by ID.
//
// GET /v1/memories/{memory_id}/
func (UnimplementedHandler) GetMemory(ctx context.Context, params GetMemoryParams) (r GetMemoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemoryHistory implements getMemoryHistory operation.
//
// Access memory change history.
//
// GET /v1/memories/{memory_id}/history/
func (UnimplementedHandler) GetMemoryHistory(ctx context.Context, params GetMemoryHistoryParams) (r GetMemoryHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchMemories implements searchMemories operation.
//
// Performs hybrid search combining semantic, BM25, and entity matching.
//
// POST /v3/memories/search/
func (UnimplementedHandler) SearchMemories(ctx context.Context, req *SearchMemoriesRequest) (r SearchMemoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMemory implements updateMemory operation.
//
// Modify an existing memory record.
//
// PUT /v1/memories/{memory_id}/
func (UnimplementedHandler) UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, params UpdateMemoryParams) (r UpdateMemoryRes, _ error) {
	return r, ht.ErrNotImplemented
}
