// Code generated by ogen, DO NOT EDIT.

package ogenhosted

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteAllMemoriesParams is parameters of deleteAllMemories operation.
type DeleteAllMemoriesParams struct {
	UserID  OptString `json:",omitempty,omitzero"`
	AgentID OptString `json:",omitempty,omitzero"`
	AppID   OptString `json:",omitempty,omitzero"`
	RunID   OptString `json:",omitempty,omitzero"`
}

func unpackDeleteAllMemoriesParams(packed middleware.Parameters) (params DeleteAllMemoriesParams) {
	{
		key := middleware.ParameterKey{
			Name: "user_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.UserID = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "agent_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AgentID = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "app_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.AppID = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "run_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.RunID = v.(OptString)
		}
	}
	return params
}

func decodeDeleteAllMemoriesParams(args [0]string, argsEscaped bool, r *http.Request) (params DeleteAllMemoriesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: user_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "user_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotUserIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotUserIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.UserID.SetTo(paramsDotUserIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "user_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: agent_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "agent_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAgentIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAgentIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AgentID.SetTo(paramsDotAgentIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "agent_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: app_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "app_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotAppIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotAppIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.AppID.SetTo(paramsDotAppIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "app_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: run_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "run_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotRunIDVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotRunIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.RunID.SetTo(paramsDotRunIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "run_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteEntityParams is parameters of deleteEntity operation.
type DeleteEntityParams struct {
	EntityType DeleteEntityEntityType
	EntityID   string
}

func unpackDeleteEntityParams(packed middleware.Parameters) (params DeleteEntityParams) {
	{
		key := middleware.ParameterKey{
			Name: "entity_type",
			In:   "path",
		}
		params.EntityType = packed[key].(DeleteEntityEntityType)
	}
	{
		key := middleware.ParameterKey{
			Name: "entity_id",
			In:   "path",
		}
		params.EntityID = packed[key].(string)
	}
	return params
}

func decodeDeleteEntityParams(args [2]string, argsEscaped bool, r *http.Request) (params DeleteEntityParams, _ error) {
	// Decode path: entity_type.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entity_type",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EntityType = DeleteEntityEntityType(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.EntityType.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entity_type",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: entity_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entity_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EntityID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entity_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteMemoryParams is parameters of deleteMemory operation.
type DeleteMemoryParams struct {
	MemoryID string
}

func unpackDeleteMemoryParams(packed middleware.Parameters) (params DeleteMemoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "memory_id",
			In:   "path",
		}
		params.MemoryID = packed[key].(string)
	}
	return params
}

func decodeDeleteMemoryParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteMemoryParams, _ error) {
	// Decode path: memory_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memory_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MemoryID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memory_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEntityParams is parameters of getEntity operation.
type GetEntityParams struct {
	EntityType GetEntityEntityType
	EntityID   string
}

func unpackGetEntityParams(packed middleware.Parameters) (params GetEntityParams) {
	{
		key := middleware.ParameterKey{
			Name: "entity_type",
			In:   "path",
		}
		params.EntityType = packed[key].(GetEntityEntityType)
	}
	{
		key := middleware.ParameterKey{
			Name: "entity_id",
			In:   "path",
		}
		params.EntityID = packed[key].(string)
	}
	return params
}

func decodeGetEntityParams(args [2]string, argsEscaped bool, r *http.Request) (params GetEntityParams, _ error) {
	// Decode path: entity_type.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entity_type",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EntityType = GetEntityEntityType(c)
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := params.EntityType.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entity_type",
			In:   "path",
			Err:  err,
		}
	}
	// Decode path: entity_id.
	if err := func() error {
		param := args[1]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[1])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "entity_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EntityID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "entity_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetEventStatusParams is parameters of getEventStatus operation.
type GetEventStatusParams struct {
	EventID string
}

func unpackGetEventStatusParams(packed middleware.Parameters) (params GetEventStatusParams) {
	{
		key := middleware.ParameterKey{
			Name: "event_id",
			In:   "path",
		}
		params.EventID = packed[key].(string)
	}
	return params
}

func decodeGetEventStatusParams(args [1]string, argsEscaped bool, r *http.Request) (params GetEventStatusParams, _ error) {
	// Decode path: event_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "event_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.EventID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "event_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMemoryParams is parameters of getMemory operation.
type GetMemoryParams struct {
	MemoryID string
}

func unpackGetMemoryParams(packed middleware.Parameters) (params GetMemoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "memory_id",
			In:   "path",
		}
		params.MemoryID = packed[key].(string)
	}
	return params
}

func decodeGetMemoryParams(args [1]string, argsEscaped bool, r *http.Request) (params GetMemoryParams, _ error) {
	// Decode path: memory_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memory_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MemoryID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memory_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetMemoryHistoryParams is parameters of getMemoryHistory operation.
type GetMemoryHistoryParams struct {
	MemoryID string
}

func unpackGetMemoryHistoryParams(packed middleware.Parameters) (params GetMemoryHistoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "memory_id",
			In:   "path",
		}
		params.MemoryID = packed[key].(string)
	}
	return params
}

func decodeGetMemoryHistoryParams(args [1]string, argsEscaped bool, r *http.Request) (params GetMemoryHistoryParams, _ error) {
	// Decode path: memory_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memory_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MemoryID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memory_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateMemoryParams is parameters of updateMemory operation.
type UpdateMemoryParams struct {
	MemoryID string
}

func unpackUpdateMemoryParams(packed middleware.Parameters) (params UpdateMemoryParams) {
	{
		key := middleware.ParameterKey{
			Name: "memory_id",
			In:   "path",
		}
		params.MemoryID = packed[key].(string)
	}
	return params
}

func decodeUpdateMemoryParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateMemoryParams, _ error) {
	// Decode path: memory_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "memory_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.MemoryID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "memory_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
