// Code generated by ogen, DO NOT EDIT.

package ogenhosted

// OperationName is the ogen operation name
type OperationName = string

const (
	AddMemoryOperation         OperationName = "AddMemory"
	DeleteAllMemoriesOperation OperationName = "DeleteAllMemories"
	DeleteEntityOperation      OperationName = "DeleteEntity"
	DeleteMemoryOperation      OperationName = "DeleteMemory"
	GetEntityOperation         OperationName = "GetEntity"
	GetEventStatusOperation    OperationName = "GetEventStatus"
	GetMemoriesOperation       OperationName = "GetMemories"
	GetMemoryOperation         OperationName = "GetMemory"
	GetMemoryHistoryOperation  OperationName = "GetMemoryHistory"
	SearchMemoriesOperation    OperationName = "SearchMemories"
	UpdateMemoryOperation      OperationName = "UpdateMemory"
)
