// Code generated by ogen, DO NOT EDIT.
package ogenhosted

type AddMemoryRes interface {
	addMemoryRes()
}

type DeleteEntityRes interface {
	deleteEntityRes()
}

type DeleteMemoryRes interface {
	deleteMemoryRes()
}

type GetEntityRes interface {
	getEntityRes()
}

type GetEventStatusRes interface {
	getEventStatusRes()
}

type GetMemoriesRes interface {
	getMemoriesRes()
}

type GetMemoryHistoryRes interface {
	getMemoryHistoryRes()
}

type GetMemoryRes interface {
	getMemoryRes()
}

type SearchMemoriesRes interface {
	searchMemoriesRes()
}

type UpdateMemoryRes interface {
	updateMemoryRes()
}
